name: Update Sports EPG

on:
  schedule:
    - cron: '0 * * * *' # S'exécute toutes les heures
  workflow_dispatch: # Permet de le lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pytz
        
      - name: Check structure
        run: find . -maxdepth 2 -not -path '*/.*'

      - name: Run script
        run: python ./generate_epg.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "EPG-Bot"
          git config --global user.email "bot@github.com"
          git add epg_sports.xml
          git commit -m "Mise à jour de l'EPG $(date)" || exit 0
          git push

